package dao.sys;

import java.util.List;

import model.sys.T_factory;
import model.sys.T_factoryExample;

import org.apache.ibatis.annotations.Param;

public interface T_factoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int countByExample(T_factoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int deleteByExample(T_factoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int deleteByPrimaryKey(Integer factory_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int insert(T_factory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int insertSelective(T_factory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	List<T_factory> selectByExample(T_factoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	T_factory selectByPrimaryKey(Integer factory_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int updateByExampleSelective(@Param("record") T_factory record,
			@Param("example") T_factoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int updateByExample(@Param("record") T_factory record,
			@Param("example") T_factoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int updateByPrimaryKeySelective(T_factory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_factory
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	int updateByPrimaryKey(T_factory record);
}