package dao;

import java.util.List;
import model.T_monitorinfo;
import model.T_monitorinfoExample;
import org.apache.ibatis.annotations.Param;

public interface T_monitorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int countByExample(T_monitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int deleteByExample(T_monitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int insert(T_monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int insertSelective(T_monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    List<T_monitorinfo> selectByExample(T_monitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    T_monitorinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int updateByExampleSelective(@Param("record") T_monitorinfo record, @Param("example") T_monitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int updateByExample(@Param("record") T_monitorinfo record, @Param("example") T_monitorinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int updateByPrimaryKeySelective(T_monitorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_monitorinfo
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    int updateByPrimaryKey(T_monitorinfo record);
}