package model.sys;

import java.util.Date;

public class T_factory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.factory_id
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer factory_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.factory_database
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String factory_database;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_ip
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_port
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_usr
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_usr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_pwd
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_encoded
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_encoded;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_address
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_contact_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_contact_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_linkman
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_linkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_telephone
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_contract_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_contract_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_opening_time
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Date fac_opening_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_contract_period
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Date fac_contract_period;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_day_handle_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_day_handle_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_process_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_process_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_regionalID
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_regionalID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_effluent_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_effluent_standard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_PLC_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_PLC_brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_PLC_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_PLC_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_PLC_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_PLC_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_configuration_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_configuration_brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_model_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_model_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_point_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_point_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_connect_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_connect_brand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_connect_model
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_connect_model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_connect_state
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Boolean fac_connect_state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_company_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_company_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_company_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_company_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_index_url
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_index_url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_design_institute
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_design_institute;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_supervision
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_supervision;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_craft_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_craft_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_report_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_report_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_equip_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_equip_amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_construction_company
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_construction_company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_areas_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_areas_longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_areas_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_areas_latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_standard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_monitoring_point
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Integer fac_monitoring_point;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_isoverproof
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private Boolean fac_isoverproof;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_factory.fac_actionphonenumber
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	private String fac_actionphonenumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.factory_id
	 * @return  the value of t_factory.factory_id
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFactory_id() {
		return factory_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.factory_id
	 * @param factory_id  the value for t_factory.factory_id
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFactory_id(Integer factory_id) {
		this.factory_id = factory_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_name
	 * @return  the value of t_factory.fac_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_name() {
		return fac_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_name
	 * @param fac_name  the value for t_factory.fac_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_name(String fac_name) {
		this.fac_name = fac_name == null ? null : fac_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.factory_database
	 * @return  the value of t_factory.factory_database
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFactory_database() {
		return factory_database;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.factory_database
	 * @param factory_database  the value for t_factory.factory_database
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFactory_database(String factory_database) {
		this.factory_database = factory_database == null ? null
				: factory_database.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_ip
	 * @return  the value of t_factory.fac_ip
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_ip() {
		return fac_ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_ip
	 * @param fac_ip  the value for t_factory.fac_ip
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_ip(String fac_ip) {
		this.fac_ip = fac_ip == null ? null : fac_ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_port
	 * @return  the value of t_factory.fac_port
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_port() {
		return fac_port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_port
	 * @param fac_port  the value for t_factory.fac_port
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_port(Integer fac_port) {
		this.fac_port = fac_port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_usr
	 * @return  the value of t_factory.fac_usr
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_usr() {
		return fac_usr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_usr
	 * @param fac_usr  the value for t_factory.fac_usr
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_usr(String fac_usr) {
		this.fac_usr = fac_usr == null ? null : fac_usr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_pwd
	 * @return  the value of t_factory.fac_pwd
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_pwd() {
		return fac_pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_pwd
	 * @param fac_pwd  the value for t_factory.fac_pwd
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_pwd(String fac_pwd) {
		this.fac_pwd = fac_pwd == null ? null : fac_pwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_encoded
	 * @return  the value of t_factory.fac_encoded
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_encoded() {
		return fac_encoded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_encoded
	 * @param fac_encoded  the value for t_factory.fac_encoded
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_encoded(String fac_encoded) {
		this.fac_encoded = fac_encoded == null ? null : fac_encoded.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_address
	 * @return  the value of t_factory.fac_address
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_address() {
		return fac_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_address
	 * @param fac_address  the value for t_factory.fac_address
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_address(String fac_address) {
		this.fac_address = fac_address == null ? null : fac_address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_contact_number
	 * @return  the value of t_factory.fac_contact_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_contact_number() {
		return fac_contact_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_contact_number
	 * @param fac_contact_number  the value for t_factory.fac_contact_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_contact_number(String fac_contact_number) {
		this.fac_contact_number = fac_contact_number == null ? null
				: fac_contact_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_linkman
	 * @return  the value of t_factory.fac_linkman
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_linkman() {
		return fac_linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_linkman
	 * @param fac_linkman  the value for t_factory.fac_linkman
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_linkman(String fac_linkman) {
		this.fac_linkman = fac_linkman == null ? null : fac_linkman.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_telephone
	 * @return  the value of t_factory.fac_telephone
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_telephone() {
		return fac_telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_telephone
	 * @param fac_telephone  the value for t_factory.fac_telephone
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_telephone(String fac_telephone) {
		this.fac_telephone = fac_telephone == null ? null : fac_telephone
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_contract_number
	 * @return  the value of t_factory.fac_contract_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_contract_number() {
		return fac_contract_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_contract_number
	 * @param fac_contract_number  the value for t_factory.fac_contract_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_contract_number(String fac_contract_number) {
		this.fac_contract_number = fac_contract_number == null ? null
				: fac_contract_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_opening_time
	 * @return  the value of t_factory.fac_opening_time
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Date getFac_opening_time() {
		return fac_opening_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_opening_time
	 * @param fac_opening_time  the value for t_factory.fac_opening_time
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_opening_time(Date fac_opening_time) {
		this.fac_opening_time = fac_opening_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_contract_period
	 * @return  the value of t_factory.fac_contract_period
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Date getFac_contract_period() {
		return fac_contract_period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_contract_period
	 * @param fac_contract_period  the value for t_factory.fac_contract_period
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_contract_period(Date fac_contract_period) {
		this.fac_contract_period = fac_contract_period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_day_handle_amount
	 * @return  the value of t_factory.fac_day_handle_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_day_handle_amount() {
		return fac_day_handle_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_day_handle_amount
	 * @param fac_day_handle_amount  the value for t_factory.fac_day_handle_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_day_handle_amount(Integer fac_day_handle_amount) {
		this.fac_day_handle_amount = fac_day_handle_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_process_type
	 * @return  the value of t_factory.fac_process_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_process_type() {
		return fac_process_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_process_type
	 * @param fac_process_type  the value for t_factory.fac_process_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_process_type(String fac_process_type) {
		this.fac_process_type = fac_process_type == null ? null
				: fac_process_type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_regionalID
	 * @return  the value of t_factory.fac_regionalID
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_regionalID() {
		return fac_regionalID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_regionalID
	 * @param fac_regionalID  the value for t_factory.fac_regionalID
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_regionalID(Integer fac_regionalID) {
		this.fac_regionalID = fac_regionalID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_effluent_standard
	 * @return  the value of t_factory.fac_effluent_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_effluent_standard() {
		return fac_effluent_standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_effluent_standard
	 * @param fac_effluent_standard  the value for t_factory.fac_effluent_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_effluent_standard(String fac_effluent_standard) {
		this.fac_effluent_standard = fac_effluent_standard == null ? null
				: fac_effluent_standard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_PLC_brand
	 * @return  the value of t_factory.fac_PLC_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_PLC_brand() {
		return fac_PLC_brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_PLC_brand
	 * @param fac_PLC_brand  the value for t_factory.fac_PLC_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_PLC_brand(String fac_PLC_brand) {
		this.fac_PLC_brand = fac_PLC_brand == null ? null : fac_PLC_brand
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_PLC_number
	 * @return  the value of t_factory.fac_PLC_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_PLC_number() {
		return fac_PLC_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_PLC_number
	 * @param fac_PLC_number  the value for t_factory.fac_PLC_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_PLC_number(String fac_PLC_number) {
		this.fac_PLC_number = fac_PLC_number == null ? null : fac_PLC_number
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_PLC_amount
	 * @return  the value of t_factory.fac_PLC_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_PLC_amount() {
		return fac_PLC_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_PLC_amount
	 * @param fac_PLC_amount  the value for t_factory.fac_PLC_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_PLC_amount(Integer fac_PLC_amount) {
		this.fac_PLC_amount = fac_PLC_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_configuration_brand
	 * @return  the value of t_factory.fac_configuration_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_configuration_brand() {
		return fac_configuration_brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_configuration_brand
	 * @param fac_configuration_brand  the value for t_factory.fac_configuration_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_configuration_brand(String fac_configuration_brand) {
		this.fac_configuration_brand = fac_configuration_brand == null ? null
				: fac_configuration_brand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_model_number
	 * @return  the value of t_factory.fac_model_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_model_number() {
		return fac_model_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_model_number
	 * @param fac_model_number  the value for t_factory.fac_model_number
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_model_number(String fac_model_number) {
		this.fac_model_number = fac_model_number == null ? null
				: fac_model_number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_point_amount
	 * @return  the value of t_factory.fac_point_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_point_amount() {
		return fac_point_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_point_amount
	 * @param fac_point_amount  the value for t_factory.fac_point_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_point_amount(Integer fac_point_amount) {
		this.fac_point_amount = fac_point_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_connect_brand
	 * @return  the value of t_factory.fac_connect_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_connect_brand() {
		return fac_connect_brand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_connect_brand
	 * @param fac_connect_brand  the value for t_factory.fac_connect_brand
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_connect_brand(String fac_connect_brand) {
		this.fac_connect_brand = fac_connect_brand == null ? null
				: fac_connect_brand.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_connect_model
	 * @return  the value of t_factory.fac_connect_model
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_connect_model() {
		return fac_connect_model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_connect_model
	 * @param fac_connect_model  the value for t_factory.fac_connect_model
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_connect_model(String fac_connect_model) {
		this.fac_connect_model = fac_connect_model == null ? null
				: fac_connect_model.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_connect_state
	 * @return  the value of t_factory.fac_connect_state
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Boolean getFac_connect_state() {
		return fac_connect_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_connect_state
	 * @param fac_connect_state  the value for t_factory.fac_connect_state
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_connect_state(Boolean fac_connect_state) {
		this.fac_connect_state = fac_connect_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_company_name
	 * @return  the value of t_factory.fac_company_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_company_name() {
		return fac_company_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_company_name
	 * @param fac_company_name  the value for t_factory.fac_company_name
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_company_name(String fac_company_name) {
		this.fac_company_name = fac_company_name == null ? null
				: fac_company_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_company_type
	 * @return  the value of t_factory.fac_company_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_company_type() {
		return fac_company_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_company_type
	 * @param fac_company_type  the value for t_factory.fac_company_type
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_company_type(Integer fac_company_type) {
		this.fac_company_type = fac_company_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_index_url
	 * @return  the value of t_factory.fac_index_url
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_index_url() {
		return fac_index_url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_index_url
	 * @param fac_index_url  the value for t_factory.fac_index_url
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_index_url(String fac_index_url) {
		this.fac_index_url = fac_index_url == null ? null : fac_index_url
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_design_institute
	 * @return  the value of t_factory.fac_design_institute
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_design_institute() {
		return fac_design_institute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_design_institute
	 * @param fac_design_institute  the value for t_factory.fac_design_institute
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_design_institute(String fac_design_institute) {
		this.fac_design_institute = fac_design_institute == null ? null
				: fac_design_institute.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_supervision
	 * @return  the value of t_factory.fac_supervision
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_supervision() {
		return fac_supervision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_supervision
	 * @param fac_supervision  the value for t_factory.fac_supervision
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_supervision(String fac_supervision) {
		this.fac_supervision = fac_supervision == null ? null : fac_supervision
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_craft_amount
	 * @return  the value of t_factory.fac_craft_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_craft_amount() {
		return fac_craft_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_craft_amount
	 * @param fac_craft_amount  the value for t_factory.fac_craft_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_craft_amount(Integer fac_craft_amount) {
		this.fac_craft_amount = fac_craft_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_report_amount
	 * @return  the value of t_factory.fac_report_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_report_amount() {
		return fac_report_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_report_amount
	 * @param fac_report_amount  the value for t_factory.fac_report_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_report_amount(Integer fac_report_amount) {
		this.fac_report_amount = fac_report_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_equip_amount
	 * @return  the value of t_factory.fac_equip_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_equip_amount() {
		return fac_equip_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_equip_amount
	 * @param fac_equip_amount  the value for t_factory.fac_equip_amount
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_equip_amount(Integer fac_equip_amount) {
		this.fac_equip_amount = fac_equip_amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_construction_company
	 * @return  the value of t_factory.fac_construction_company
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_construction_company() {
		return fac_construction_company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_construction_company
	 * @param fac_construction_company  the value for t_factory.fac_construction_company
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_construction_company(String fac_construction_company) {
		this.fac_construction_company = fac_construction_company == null ? null
				: fac_construction_company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_areas_longitude
	 * @return  the value of t_factory.fac_areas_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_areas_longitude() {
		return fac_areas_longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_areas_longitude
	 * @param fac_areas_longitude  the value for t_factory.fac_areas_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_areas_longitude(String fac_areas_longitude) {
		this.fac_areas_longitude = fac_areas_longitude == null ? null
				: fac_areas_longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_areas_latitude
	 * @return  the value of t_factory.fac_areas_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_areas_latitude() {
		return fac_areas_latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_areas_latitude
	 * @param fac_areas_latitude  the value for t_factory.fac_areas_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_areas_latitude(String fac_areas_latitude) {
		this.fac_areas_latitude = fac_areas_latitude == null ? null
				: fac_areas_latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_longitude
	 * @return  the value of t_factory.fac_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_longitude() {
		return fac_longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_longitude
	 * @param fac_longitude  the value for t_factory.fac_longitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_longitude(String fac_longitude) {
		this.fac_longitude = fac_longitude == null ? null : fac_longitude
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_latitude
	 * @return  the value of t_factory.fac_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_latitude() {
		return fac_latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_latitude
	 * @param fac_latitude  the value for t_factory.fac_latitude
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_latitude(String fac_latitude) {
		this.fac_latitude = fac_latitude == null ? null : fac_latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_standard
	 * @return  the value of t_factory.fac_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_standard() {
		return fac_standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_standard
	 * @param fac_standard  the value for t_factory.fac_standard
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_standard(Integer fac_standard) {
		this.fac_standard = fac_standard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_monitoring_point
	 * @return  the value of t_factory.fac_monitoring_point
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Integer getFac_monitoring_point() {
		return fac_monitoring_point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_monitoring_point
	 * @param fac_monitoring_point  the value for t_factory.fac_monitoring_point
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_monitoring_point(Integer fac_monitoring_point) {
		this.fac_monitoring_point = fac_monitoring_point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_isoverproof
	 * @return  the value of t_factory.fac_isoverproof
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public Boolean getFac_isoverproof() {
		return fac_isoverproof;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_isoverproof
	 * @param fac_isoverproof  the value for t_factory.fac_isoverproof
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_isoverproof(Boolean fac_isoverproof) {
		this.fac_isoverproof = fac_isoverproof;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_factory.fac_actionphonenumber
	 * @return  the value of t_factory.fac_actionphonenumber
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public String getFac_actionphonenumber() {
		return fac_actionphonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_factory.fac_actionphonenumber
	 * @param fac_actionphonenumber  the value for t_factory.fac_actionphonenumber
	 * @mbggenerated  Wed Feb 04 14:20:43 CST 2015
	 */
	public void setFac_actionphonenumber(String fac_actionphonenumber) {
		this.fac_actionphonenumber = fac_actionphonenumber == null ? null
				: fac_actionphonenumber.trim();
	}
}