package model;

public class T_monitorinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.program_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String program_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.program_type
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String program_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.group_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private Integer group_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.plc_address
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String plc_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.monitor_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String monitor_table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.count_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String count_table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.program_desc
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String program_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.local_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String local_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.program_unit
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private String program_unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_monitorinfo.program_chart
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    private Integer program_chart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.id
     *
     * @return the value of t_monitorinfo.id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.id
     *
     * @param id the value for t_monitorinfo.id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.program_id
     *
     * @return the value of t_monitorinfo.program_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getProgram_id() {
        return program_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.program_id
     *
     * @param program_id the value for t_monitorinfo.program_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setProgram_id(String program_id) {
        this.program_id = program_id == null ? null : program_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.program_type
     *
     * @return the value of t_monitorinfo.program_type
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getProgram_type() {
        return program_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.program_type
     *
     * @param program_type the value for t_monitorinfo.program_type
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setProgram_type(String program_type) {
        this.program_type = program_type == null ? null : program_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.group_id
     *
     * @return the value of t_monitorinfo.group_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public Integer getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.group_id
     *
     * @param group_id the value for t_monitorinfo.group_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.plc_address
     *
     * @return the value of t_monitorinfo.plc_address
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getPlc_address() {
        return plc_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.plc_address
     *
     * @param plc_address the value for t_monitorinfo.plc_address
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setPlc_address(String plc_address) {
        this.plc_address = plc_address == null ? null : plc_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.monitor_table
     *
     * @return the value of t_monitorinfo.monitor_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getMonitor_table() {
        return monitor_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.monitor_table
     *
     * @param monitor_table the value for t_monitorinfo.monitor_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setMonitor_table(String monitor_table) {
        this.monitor_table = monitor_table == null ? null : monitor_table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.count_table
     *
     * @return the value of t_monitorinfo.count_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getCount_table() {
        return count_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.count_table
     *
     * @param count_table the value for t_monitorinfo.count_table
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setCount_table(String count_table) {
        this.count_table = count_table == null ? null : count_table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.program_desc
     *
     * @return the value of t_monitorinfo.program_desc
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getProgram_desc() {
        return program_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.program_desc
     *
     * @param program_desc the value for t_monitorinfo.program_desc
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setProgram_desc(String program_desc) {
        this.program_desc = program_desc == null ? null : program_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.local_id
     *
     * @return the value of t_monitorinfo.local_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getLocal_id() {
        return local_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.local_id
     *
     * @param local_id the value for t_monitorinfo.local_id
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setLocal_id(String local_id) {
        this.local_id = local_id == null ? null : local_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.program_unit
     *
     * @return the value of t_monitorinfo.program_unit
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public String getProgram_unit() {
        return program_unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.program_unit
     *
     * @param program_unit the value for t_monitorinfo.program_unit
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setProgram_unit(String program_unit) {
        this.program_unit = program_unit == null ? null : program_unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_monitorinfo.program_chart
     *
     * @return the value of t_monitorinfo.program_chart
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public Integer getProgram_chart() {
        return program_chart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_monitorinfo.program_chart
     *
     * @param program_chart the value for t_monitorinfo.program_chart
     *
     * @mbggenerated Mon Nov 24 11:21:54 CST 2014
     */
    public void setProgram_chart(Integer program_chart) {
        this.program_chart = program_chart;
    }
}